[boot]
systemd=true
command="/usr/local/bin/update-wsl-ip.sh  && service pihole-FTL start && service nginx start && service prometheus start && service grafana-server start && service apache2 start && service mariadb start && wg-quick up wg0"

[user]
default=<USERNAME> # Replace with your username you set up for WSL/Ubuntu
